document.addEventListener('DOMContentLoaded',function(){const userProfile={gender:"",user_looking_gender:"",username:"",user_Dob:"",email:"",password:""}
let timeLeft=5*60;let timerElement=document.getElementById("countdown-timer");let timerId;function updateTimerDisplay(){let minutes=Math.floor(timeLeft/60);let seconds=timeLeft%60;seconds=seconds<10?'0'+seconds:seconds;timerElement.textContent=minutes+":"+seconds;if(timeLeft<60){timerElement.classList.add("last-minute")}
if(timeLeft<=0){clearInterval(timerId);timerElement.textContent="Time's up!";document.querySelector('#btn-choose-your-gender').disabled=!0;document.querySelector('#btn-choose-gender-looking').disabled=!0;document.querySelector('#btn-profile-info').disabled=!0;document.querySelector('#btn-profile-details').disabled=!0}}
function startTimer(){timerId=setInterval(function(){timeLeft-=1;updateTimerDisplay()},1000)}
startTimer();document.addEventListener("visibilitychange",function(){(document.visibilityState==='visible')?startTimer():clearInterval(timerId)});const stepOne=document.querySelector('.step-one');const stepTwo=document.querySelector('.step-two');const stepThree=document.querySelector('.step-three');const stepFour=document.querySelector('.step-four');const stepFive=document.querySelector('.step-five');const stepSix=document.querySelector('.step-six');const stepLevelOne=document.querySelector('.step-level-one');const stepLevelTwo=document.querySelector('.step-level-two');const stepLevelThree=document.querySelector('.step-level-three');const stepLevelFour=document.querySelector('.step-level-four');const stepLevelFive=document.querySelector('.step-level-five');const stepLevelSix=document.querySelector('.step-level-six');const btnMoveToStepThree=document.querySelector('#btn-choose-your-gender');const btnMoveToStepFour=document.querySelector('#btn-choose-gender-looking');const btnMoveToStepFive=document.querySelector('#btn-profile-info');const btnMoveToStepFinal=document.querySelector('#btn-profile-details');const btnContinue=document.querySelector('#btn-continue')
function moveToNextStep(currentStep,stepLevel,nextStep,nextStepLevel,nextStepNextBtn){currentStep.classList.remove('flex');currentStep.classList.add('hidden');stepLevel.classList.remove('current-step')
nextStep.classList.remove('hidden');nextStep.classList.add('flex');nextStepLevel.classList.add('current-step');if(nextStepNextBtn){nextStepNextBtn.disabled=!0}}
const selectGender=(choice,opposite,item,value,nextButton)=>{choice.style.background="#FD7401";opposite.style.background="#171717";userProfile[item]=value;nextButton.disabled=!1}
const validateEmail=(email)=>/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(email);const btnEmail=document.querySelector('#register-with-email');btnEmail.addEventListener('click',()=>{moveToNextStep(stepOne,stepLevelOne,stepTwo,stepLevelTwo,btnMoveToStepThree)})
const genderMaleChoice=document.querySelector('#choose-gender-male');const genderFemaleChoice=document.querySelector('#choose-gender-female');genderMaleChoice.addEventListener('click',()=>{selectGender(genderMaleChoice,genderFemaleChoice,'gender',"Male",btnMoveToStepThree)});genderFemaleChoice.addEventListener('click',()=>{selectGender(genderFemaleChoice,genderMaleChoice,'gender',"Female",btnMoveToStepThree)});btnMoveToStepThree.addEventListener('click',()=>{moveToNextStep(stepTwo,stepLevelTwo,stepThree,stepLevelThree,btnMoveToStepFour)})
const genderLookingForMaleChoice=document.querySelector('#looking-for-male');const genderLookingForFemaleChoice=document.querySelector('#looking-for-female');genderLookingForMaleChoice.addEventListener('click',()=>{selectGender(genderLookingForMaleChoice,genderLookingForFemaleChoice,'user_looking_gender',"Male",btnMoveToStepFour)});genderLookingForFemaleChoice.addEventListener('click',()=>{selectGender(genderLookingForFemaleChoice,genderLookingForMaleChoice,'gender',"Female",btnMoveToStepFour)});btnMoveToStepFour.addEventListener('click',()=>{moveToNextStep(stepThree,stepLevelThree,stepFour,stepLevelFour,btnMoveToStepFive)})
const username=document.querySelector('#username');const usernameError=document.querySelector('.username-error');username.addEventListener('change',function(){userProfile.username=username.value;if(userProfile.username.length>4){username.style.border='none'
usernameError.classList.remove('flex')
usernameError.classList.add('hidden')
btnMoveToStepFive.disabled=!(userProfile.username&&userProfile.user_Dob)}else{username.style.border='1px solid red'
usernameError.classList.remove('hidden')
usernameError.classList.add('flex')}});const dobPicker=document.getElementById('dob');const today=new Date();const minAge=18;const maxValidDate=new Date(today.getFullYear()-minAge,today.getMonth(),today.getDate()).toISOString().split('T')[0];dobPicker.setAttribute("max",maxValidDate);dobPicker.addEventListener('change',function(){userProfile.user_Dob=this.value;btnMoveToStepFive.disabled=!userProfile.user_Dob||!userProfile.username});btnMoveToStepFive.addEventListener('click',()=>{moveToNextStep(stepFour,stepLevelFour,stepFive,stepLevelFive,btnMoveToStepFinal)});const email=document.querySelector('#email');const password=document.querySelector('#password');const emailError=document.querySelector('.email-error');email.addEventListener('change',function(){userProfile.email=email.value;if(validateEmail(email.value)){email.style.border='none'
emailError.classList.remove('flex')
emailError.classList.add('hidden')
btnMoveToStepFinal.disabled=!(userProfile.password&&userProfile.email)}else{email.style.border='1px solid red'
emailError.classList.remove('hidden')
emailError.classList.add('flex')}})
password.addEventListener('change',function(){userProfile.password=password.value;btnMoveToStepFinal.disabled=!(userProfile.password&&validateEmail(userProfile.email))})
btnMoveToStepFinal.addEventListener('click',()=>{moveToNextStep(stepFive,stepLevelFive,stepSix,stepLevelSix,btnContinue)})
const tAndCsAgreement=document.querySelector('#tandcs');tAndCsAgreement.addEventListener('change',function(){if(this.checked){btnContinue.disabled=!1;btnContinue.classList.remove('hidden')
btnContinue.classList.add('flex')}else{btnContinue.disabled=!0}})})